name: tavtestproject1
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Bloc for state management  #  https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^4.0.1
  # Value equality  #  https://pub.dev/packages/equatable
  equatable: ^1.2.0
  # Functional programming thingies  #  https://pub.dev/packages/dartz
  dartz: ^0.9.0
  # DB  #  https://pub.dev/packages/sembast
  sembast: ^2.4.5
  # Path provider  #  https://pub.dev/packages/path_provider
  path_provider: ^1.6.11
  # Image picker  #  https://pub.dev/packages/image_picker
  image_picker: ^0.6.7+2
  # Translate  #  https://pub.dev/packages/flutter_translate
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.0
  flutter_localizations:
    sdk: flutter
  # Settings UI  #  https://github.com/yako-dev/flutter-settings-ui
  settings_ui: ^0.3.0
  # Awesome fonts  #  https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 8.8.1
  # Color picker  #  https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker: ^0.3.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Build runner  #  https://pub.dev/packages/build_runner
  build_runner: ^1.10.0
  # Translate  #  https://pub.dev/packages/flutter_translate
  flutter_translate_gen: ^1.2.1



flutter:
  uses-material-design: true

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iransans.ttf
    - family: BuonUmore
      fonts:
        - asset: assets/fonts/buon_umore.ttf
    - family: SchoolBuild
      fonts:
        - asset: assets/fonts/school_build.ttf
    - family: Emejing
      fonts:
        - asset: assets/fonts/emejing.otf
    - family: Geometria
      fonts:
        - asset: assets/fonts/geometria.ttf

  assets:
    - assets/images/
    - assets/i18n/
